### PR TITLE
Fix for new OnGiveXP

### PR DESCRIPTION
**Pull request by V-Cyberpunk**

### CODE REVIEW

**Comment by Helias** [comment]
update your PR with master to make work the pipeline and overcome the Configure OS step

but unfortunaltey this module needs some updates because the build with this module is failing

```
/home/runner/work/mod-solocraft/mod-solocraft/modules/mod-solocraft/src/Solocraft.cpp:343:70: fatal error: non-virtual member function marked 'override' hides virtual member function
        void OnGiveXP(Player* /*player*/, uint32& amount, Unit* /*victim*/) override
                                                                            ^
/home/runner/work/mod-solocraft/mod-solocraft/src/server/game/Scripting/ScriptMgr.h:1038:18: note: hidden overloaded virtual function 'PlayerScript::OnGiveXP' declared here: different number of parameters (4 vs 3)
    virtual void OnGiveXP(Player* /*player*/, uint32& /*amount*/, Unit* /*victim*/, uint8 /*xpSource*/) { }
                 ^
1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:104: modules/CMakeFiles/modules.dir/mod-solocraft/src/Solocraft.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1199: modules/CMakeFiles/modules.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by V-Cyberpunk** [comment]
I compiled it with AC rev d282cce4af69 and works fine.

**Comment by Helias** [comment]
probably you fixed the issue in this PR, but you have to update your repo with the latest version to update the pipeline

if you do not know how to do that, use git bash to enter in your mod-solocraft directory project and run
```
git checkout fix-newXP-System
git remote add upstream https://github.com/azerothcore/mod-solocraft
git fetch upstream
git merge upstream/master
git push
```

in this way you will update your branch fix-newXP-System with the latest version of the master branch in the azerothcore repo

**Comment by V-Cyberpunk** [comment]
updated my repo :)

**Comment by Helias** [comment]
build succeed, thanks for your PR!

**Pull request merged**
